/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Lophoc;
import model.Sinhvien;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.Set;

import static GUI.DangNhap.giaoVuService;

/**
 *
 * @author lhqua
 */
public class DanhSachSinhVienTrongLop extends javax.swing.JFrame {
    private Sinhvien sinhvienChon = null;
    private Lophoc lophoc = null;
    /**
     * Creates new form DanhSachSinhVienTrongLop
     */
    public DanhSachSinhVienTrongLop(Lophoc lophocChon) {
        lophoc = lophocChon;
        initComponents();
        capNhatDanhSachSinhVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeLopHoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachSinhVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        maSinhVien = new javax.swing.JLabel();
        layMaSinhVien = new javax.swing.JTextField();
        tenSinhVien = new javax.swing.JLabel();
        layTenSinhVien = new javax.swing.JTextField();
        layGioiTinh = new javax.swing.JComboBox<>();
        gioiTinh = new javax.swing.JLabel();
        ngaySinh = new javax.swing.JLabel();
        diaChi = new javax.swing.JLabel();
        layNgaySinh = new javax.swing.JTextField();
        layDiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        themSinhVien = new javax.swing.JButton();
        capNhatSinhVien = new javax.swing.JButton();
        resetTaiKhoanSinhVien = new javax.swing.JButton();
        lamMoiDanhSach = new javax.swing.JButton();
        xoaSinhVien = new javax.swing.JButton();
        thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieuDeLopHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tieuDeLopHoc.setText("Thông Tin Lớp Học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tieuDeLopHoc)
                                .addGap(363, 363, 363))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(tieuDeLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        danhSachSinhVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Mã Sinh Viên", "Tên Sinh Viên", "Giới Tính", "Ngày Sinh", "Địa Chỉ"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        danhSachSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhSachSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(danhSachSinhVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );

        maSinhVien.setText("Mã Sinh Viên");

        tenSinhVien.setText("Tên Sinh Viên");

        layGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        gioiTinh.setText("Giới Tính");

        ngaySinh.setText("Ngày Sinh");

        diaChi.setText("Địa Chỉ");

        jLabel7.setText("YYYY-MM-DD");

        themSinhVien.setText("Thêm Sinh Viên");
        themSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSinhVienActionPerformed(evt);
            }
        });

        capNhatSinhVien.setText("Cập Nhật Sinh Viên");
        capNhatSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatSinhVienActionPerformed(evt);
            }
        });

        resetTaiKhoanSinhVien.setText("Reset Tài Khoản");
        resetTaiKhoanSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTaiKhoanSinhVienActionPerformed(evt);
            }
        });

        lamMoiDanhSach.setText("Làm Mới");
        lamMoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiDanhSachActionPerformed(evt);
            }
        });

        xoaSinhVien.setText("Xóa Sinh Viên");
        xoaSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaSinhVienActionPerformed(evt);
            }
        });

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(capNhatSinhVien)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(xoaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(themSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(resetTaiKhoanSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(lamMoiDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(themSinhVien)
                                        .addComponent(resetTaiKhoanSinhVien))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(capNhatSinhVien)
                                        .addComponent(xoaSinhVien))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lamMoiDanhSach)
                                        .addComponent(thoat))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(gioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maSinhVien, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tenSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(layTenSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                                        .addComponent(layMaSinhVien))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ngaySinh)
                                                        .addComponent(diaChi))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(layNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(layDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(layGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maSinhVien)
                                        .addComponent(layMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ngaySinh)
                                        .addComponent(layNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenSinhVien)
                                        .addComponent(layTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(diaChi)
                                        .addComponent(layDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(layGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gioiTinh))
                                .addContainerGap(33, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void capNhatSinhVienActionPerformed(java.awt.event.ActionEvent evt) {
        if(sinhvienChon != null) {
            String strNull = "";
            String maSinhVien = layMaSinhVien.getText();
            String tenSinhVien = layTenSinhVien.getText();
            String gioiTinh = layGioiTinh.getSelectedItem().toString();
            String ngaySinh = layNgaySinh.getText();
            String diaChi = layDiaChi.getText();
            if (maSinhVien.equals(strNull) || tenSinhVien.equals(strNull) || gioiTinh.equals(strNull) || ngaySinh.equals(strNull) || diaChi.equals(strNull)) {
                JOptionPane.showMessageDialog(null, "Các Ô Dữ Liệu Không Được Trống !");
                this.ResetForm();
                return;
            }
            if (ngaySinh.charAt(4) != '-' || ngaySinh.charAt(7) != '-') {
                JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
                this.ResetForm();
                return;
            }
            Date date = Date.valueOf(ngaySinh);
            if (!sinhvienChon.getMaSinhVien().equals(maSinhVien)) {
                JOptionPane.showMessageDialog(null, "Mã Sinh Viên Không Được Đổi !!");
                this.ResetForm();
                return;
            }
            sinhvienChon.setTenSinhVien(tenSinhVien);
            sinhvienChon.setGioiTinh(gioiTinh);
            sinhvienChon.setNgaySinh(date);
            sinhvienChon.setDiaChi(diaChi);
            if (giaoVuService.capNhatSinhVien(sinhvienChon)) {
                JOptionPane.showMessageDialog(this, "Sửa Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                capNhatDanhSachSinhVien();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi Không Sửa Được Mời Kiểm Tra Lại Dữ Liệu !");
                this.ResetForm();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Chưa Chọn Sinh Viên !");
            this.ResetForm();
        }
    }

    private void themSinhVienActionPerformed(java.awt.event.ActionEvent evt) {
        String strNull = "";
        String maSinhVien = layMaSinhVien.getText();
        String tenSinhVien = layTenSinhVien.getText();
        String gioiTinh = layGioiTinh.getSelectedItem().toString();
        String ngaySinh = layNgaySinh.getText();
        String diaChi = layDiaChi.getText();
        if(maSinhVien.equals(strNull) || tenSinhVien.equals(strNull) || gioiTinh.equals(strNull) || ngaySinh.equals(strNull) || diaChi.equals(strNull)){
            JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu !");
            this.ResetForm();
            return;
        }
        if(ngaySinh.charAt(4) != '-'|| ngaySinh.charAt(7) != '-' ){
            JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
            this.ResetForm();
            return;
        }
        Date date = Date.valueOf(ngaySinh);
        Sinhvien sinhvienMoi = new Sinhvien(maSinhVien,tenSinhVien,gioiTinh,date,diaChi,maSinhVien,maSinhVien,lophoc);
        if(giaoVuService.themSinhVienVaoLop(sinhvienMoi)){
            JOptionPane.showMessageDialog(this, "Thêm Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            capNhatDanhSachSinhVien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Lỗi Không Thêm Được Mời Kiểm Tra Lại Dữ Liệu !");
            this.ResetForm();
        }
    }

    private void lamMoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {
        capNhatDanhSachSinhVien();
        ResetForm();
    }

    private void resetTaiKhoanSinhVienActionPerformed(java.awt.event.ActionEvent evt) {
        if(sinhvienChon != null){
            sinhvienChon.setTaiKhoan(sinhvienChon.getMaSinhVien());
            sinhvienChon.setMatKhau(sinhvienChon.getMaSinhVien());
            if(giaoVuService.capNhatSinhVien(sinhvienChon))
            {
                JOptionPane.showMessageDialog(this, "Reset Thành Công! Tài Khoản và Mật Khẩu là Mã Sinh Viên ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                capNhatDanhSachSinhVien();
            }
            else{
                JOptionPane.showMessageDialog(null, "Reset Không Thành Công!! Mời Làm Lại");
                this.ResetForm();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Chưa Chọn Sinh Viên Cần Reset!!");
            this.ResetForm();
        }
    }

    private void xoaSinhVienActionPerformed(java.awt.event.ActionEvent evt) {
        if(sinhvienChon == null){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Sinh Viên Cần Xóa!");
            this.ResetForm();
        }
        else {
            String strNull = "";
            String maSinhVien = layMaSinhVien.getText();
            String tenSinhVien = layTenSinhVien.getText();
            String gioiTinh = layGioiTinh.getSelectedItem().toString();
            String ngaySinh = layNgaySinh.getText();
            String diaChi = layDiaChi.getText();
            if(maSinhVien.equals(strNull) || tenSinhVien.equals(strNull) || gioiTinh.equals(strNull) || ngaySinh.equals(strNull) || diaChi.equals(strNull)){
                JOptionPane.showMessageDialog(null, "Các Ô Dữ Liệu Không Được Trống!!");
                this.ResetForm();
            }
            if(ngaySinh.charAt(4) != '-'|| ngaySinh.charAt(7) != '-' ){
                JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
                this.ResetForm();
            }
            Date date = Date.valueOf(ngaySinh);
            Sinhvien sinhvienXoa = giaoVuService.laySinhVienBangMaSinhVien(maSinhVien);
            if(giaoVuService.xoaSinhVien(sinhvienXoa)){
                JOptionPane.showMessageDialog(this, "Xóa  Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                capNhatDanhSachSinhVien();
            }
            else{
                JOptionPane.showMessageDialog(null, "Xóa Không Thành Công!! Mời Kiểm Tra Lại Dữ Liệu");
                this.ResetForm();
            }
        }
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void danhSachSinhVienMouseClicked(java.awt.event.MouseEvent evt) {
        int dong = danhSachSinhVien.getSelectedRow();
        int[] cot = danhSachSinhVien.getSelectedColumns();
        String maSinhVien = String.valueOf(danhSachSinhVien.getValueAt(dong, 0));
        String tenSinhVien = String.valueOf(danhSachSinhVien.getValueAt(dong, 1));
        String gioiTinh = String.valueOf(danhSachSinhVien.getValueAt(dong, 2));
        String ngaySinh = String.valueOf(danhSachSinhVien.getValueAt(dong, 3));
        String diaChi = String.valueOf(danhSachSinhVien.getValueAt(dong, 4));
        Date date = Date.valueOf(ngaySinh);
        sinhvienChon = giaoVuService.laySinhVienBangMaSinhVien(maSinhVien);

        System.out.println(sinhvienChon.toString());
        if (sinhvienChon != null) {
            layMaSinhVien.setText(sinhvienChon.getMaSinhVien());
            layTenSinhVien.setText(sinhvienChon.getTenSinhVien());
            layNgaySinh.setText(sinhvienChon.getNgaySinh().toString());
            layDiaChi.setText(sinhvienChon.getDiaChi());
            if (sinhvienChon.getGioiTinh().equals("Nam")) {
                layGioiTinh.setSelectedIndex(0);
            } else {
                layGioiTinh.setSelectedIndex(1);
            }
        }
    }

   private void capNhatDanhSachSinhVien(){
       DefaultTableModel defaultTableModel = new DefaultTableModel();
       danhSachSinhVien.setModel(defaultTableModel);
       defaultTableModel.addColumn("Mã Sinh Viên");
       defaultTableModel.addColumn("Tên Sinh Viên");
       defaultTableModel.addColumn("Giới Tính");
       defaultTableModel.addColumn("Ngày Sinh");
       defaultTableModel.addColumn("Địa Chỉ");
       if(lophoc != null) {
           Lophoc lophocChon = giaoVuService.layThongTinLopHocBangMaLop(lophoc.getMaLop());
           Set<Sinhvien> sinhviens = lophocChon.getSinhviens();
           for (Sinhvien i : sinhviens) {
               Object[] tmp = new Object[]{i.getMaSinhVien(), i.getTenSinhVien(), i.getGioiTinh(), i.getNgaySinh(), i.getDiaChi()};
               defaultTableModel.addRow(tmp);
           }
       }
   }

    public void ResetForm() {
        layMaSinhVien.setText("");
        layTenSinhVien.setText("");
        layNgaySinh.setText("");
        layDiaChi.setText("");
        layGioiTinh.setSelectedIndex(0);
        sinhvienChon = null;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton capNhatSinhVien;
    private javax.swing.JTable danhSachSinhVien;
    private javax.swing.JLabel diaChi;
    private javax.swing.JLabel gioiTinh;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoiDanhSach;
    private javax.swing.JTextField layDiaChi;
    private javax.swing.JComboBox<String> layGioiTinh;
    private javax.swing.JTextField layMaSinhVien;
    private javax.swing.JTextField layNgaySinh;
    private javax.swing.JTextField layTenSinhVien;
    private javax.swing.JLabel maSinhVien;
    private javax.swing.JLabel ngaySinh;
    private javax.swing.JButton resetTaiKhoanSinhVien;
    private javax.swing.JLabel tenSinhVien;
    private javax.swing.JButton themSinhVien;
    private javax.swing.JButton thoat;
    private javax.swing.JLabel tieuDeLopHoc;
    private javax.swing.JButton xoaSinhVien;
    // End of variables declaration
}
