/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.*;

import static GUI.DangNhap.*;

/**
 *
 * @author lhqua
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        matKhauCu = new javax.swing.JLabel();
        matKhauMoi = new javax.swing.JLabel();
        layMatKhauCu = new javax.swing.JTextField();
        layMatKhauMoi = new javax.swing.JTextField();
        doiMatKhau = new javax.swing.JButton();
        thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matKhauCu.setText("Mật Khẩu Cũ: ");

        matKhauMoi.setText("Mật Khẩu Mới: ");

        doiMatKhau.setText("Đổi Mật Khẩu");
        doiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiMatKhauActionPerformed(evt);
            }
        });

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(matKhauCu)
                                                        .addComponent(matKhauMoi))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(layMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                        .addComponent(layMatKhauCu)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(doiMatKhau)
                                                .addGap(30, 30, 30)
                                                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(matKhauCu)
                                        .addComponent(layMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(matKhauMoi)
                                        .addComponent(layMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(doiMatKhau)
                                        .addComponent(thoat))
                                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void doiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String strNull = "";
        if(DangNhap.kiemTraNguoiDung == 0 ){
            String matKhauCu = layMatKhauCu.getText();
            String matKhauMoi = layMatKhauMoi.getText();
            if(matKhauMoi.equals(strNull) || matKhauCu.equals(strNull)){
                JOptionPane.showMessageDialog(null, "Mật khẩu cũ và mới không được trống !");
                this.resetForm();
            }
            else{
                giaovu.setMatKhau(matKhauMoi);
                if(giaoVuService.capNhatGiaoVu(giaovu))
                {
                    JOptionPane.showMessageDialog(null,"Cập Nhật Thành Công!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Cập Nhật Thất Bại!");
                }
            }
        }
        else if(kiemTraNguoiDung == 1){
            String matKhauCu = layMatKhauCu.getText();
            String matKhauMoi = layMatKhauMoi.getText();
            if(matKhauMoi.equals(strNull) || matKhauCu.equals(strNull)){
                JOptionPane.showMessageDialog(null, "Mật khẩu cũ và mới không được trống !");
                this.resetForm();
            }
            else{
                sinhvien.setMatKhau(matKhauMoi);
                if(sinhVienService.capNhatSinhVien(sinhvien))
                {
                    JOptionPane.showMessageDialog(null,"Cập Nhật Thành Công!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Cập Nhật Thất Bại!");
                }
            }
        }
        dispose();
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    public void resetForm() {
        layMatKhauCu.setText("");
        layMatKhauMoi.setText("");
        layMatKhauCu.requestFocus();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton doiMatKhau;
    private javax.swing.JTextField layMatKhauCu;
    private javax.swing.JTextField layMatKhauMoi;
    private javax.swing.JLabel matKhauCu;
    private javax.swing.JLabel matKhauMoi;
    private javax.swing.JButton thoat;
    // End of variables declaration
}
