/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Monhoc;
import model.Sinhvien;
import model.Sinhvien_Hocphan;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

import static GUI.DangNhap.giaoVuService;

/**
 *
 * @author lhqua
 */
public class FormQuanLySinhVienMonHoc extends javax.swing.JPanel {

    /**
     * Creates new form FormQuanLySinhVienMonHoc
     */
    public FormQuanLySinhVienMonHoc() {
        initComponents();
        List<Sinhvien_Hocphan> list = giaoVuService.layDanhSachSinhVien_HocPhan();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachSinhVien.setModel(defaultTableModel);
        defaultTableModel.addColumn("MSSv");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Môn Học");
        for(Sinhvien_Hocphan i : list){
            Sinhvien sinhvien = i.getSinhvien();
            Monhoc monhoc = i.getHocphanmo().getMonhoc();
            String mssv = sinhvien.getMaSinhVien();
            String tenSinhVien = sinhvien.getTenSinhVien();
            String maMonHoc = monhoc.getMaMonHoc();
            String tenMonHoc = monhoc.getTenMonHoc();
            Object[] tmp = new Object[]{mssv,tenSinhVien,maMonHoc,tenMonHoc};
            defaultTableModel.addRow(tmp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        tieuDeSinhVien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachSinhVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        maSinhVien = new javax.swing.JLabel();
        layMaSinhVien = new javax.swing.JTextField();
        timKiem = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quản Lý Sinh Viên");

        lamMoi.setText("Làm Mới");
        lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tieuDeSinhVienLayout = new javax.swing.GroupLayout(tieuDeSinhVien);
        tieuDeSinhVien.setLayout(tieuDeSinhVienLayout);
        tieuDeSinhVienLayout.setHorizontalGroup(
                tieuDeSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tieuDeSinhVienLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(268, 268, 268)
                                .addComponent(lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
        );
        tieuDeSinhVienLayout.setVerticalGroup(
                tieuDeSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tieuDeSinhVienLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tieuDeSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(lamMoi))
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        danhSachSinhVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Mã Sinh Viên", "Tên Sinh Viên", "Mã Môn Học", "Tên Môn Học"
                }
        ));
        jScrollPane1.setViewportView(danhSachSinhVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        maSinhVien.setText("Nhập Mã Sinh Viên Cần Tìm");

        timKiem.setText("Tìm Kiếm");
        timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(maSinhVien)
                                .addGap(18, 18, 18)
                                .addComponent(layMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maSinhVien)
                                        .addComponent(layMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timKiem))
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tieuDeSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(tieuDeSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>

    private void timKiemActionPerformed(java.awt.event.ActionEvent evt) {
        String strNull = "";
        String mssvCanTim = layMaSinhVien.getText();
        if(mssvCanTim.equals(strNull)){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Nhập Mã Số Sinh Viên Cần Tìm !!");
            return;
        }
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachSinhVien.setModel(defaultTableModel);
        defaultTableModel.addColumn("MSSV");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Môn Học");
        List<Sinhvien_Hocphan> list = giaoVuService.layDanhSachSinhVien_HocPhan();
        for(Sinhvien_Hocphan i : list){
            Sinhvien sinhvien = i.getSinhvien();
            Monhoc monhoc = i.getHocphanmo().getMonhoc();
            String mssv = sinhvien.getMaSinhVien();
            String tenSinhVien = sinhvien.getTenSinhVien();
            String maMonHoc = monhoc.getMaMonHoc();
            String tenMonHoc = monhoc.getTenMonHoc();
            if(mssv.equals(mssvCanTim)) {
                Object[] tmp = new Object[]{mssv, tenSinhVien, maMonHoc, tenMonHoc};
                defaultTableModel.addRow(tmp);
            }
        }
        layMaSinhVien.setText("");
        layMaSinhVien.requestFocus();
    }

    private void lamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        List<Sinhvien_Hocphan> list = giaoVuService.layDanhSachSinhVien_HocPhan();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachSinhVien.setModel(defaultTableModel);
        defaultTableModel.addColumn("MSSV");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Môn Học");
        for(Sinhvien_Hocphan i : list){
            Sinhvien sinhvien = i.getSinhvien();
            Monhoc monhoc = i.getHocphanmo().getMonhoc();
            String mssv = sinhvien.getMaSinhVien();
            String tenSinhVien = sinhvien.getTenSinhVien();
            String maMonHoc = monhoc.getMaMonHoc();
            String tenMonHoc = monhoc.getTenMonHoc();
            Object[] tmp = new Object[]{mssv,tenSinhVien,maMonHoc,tenMonHoc};
            defaultTableModel.addRow(tmp);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JTable danhSachSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoi;
    private javax.swing.JTextField layMaSinhVien;
    private javax.swing.JLabel maSinhVien;
    private javax.swing.JPanel tieuDeSinhVien;
    private javax.swing.JButton timKiem;
    // End of variables declaration
}
