/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Giaovu;
import model.Monhoc;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.List;

import static GUI.DangNhap.giaoVuService;
import static GUI.DangNhap.kiemTraNguoiDung;

/**
 *
 * @author lhqua
 */
public class FormMonHoc extends javax.swing.JPanel {
    private Monhoc monhocChon = null;
    /**
     * Creates new form FormMonHoc
     */
    public FormMonHoc() {
        initComponents();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachMonHoc.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Môn Học");
        defaultTableModel.addColumn("Số Tín Chỉ");
        if(kiemTraNguoiDung == 0) {
            List<Monhoc> listMonHoc = giaoVuService.layDanhSachMonHoc();
            for (Monhoc i : listMonHoc) {
                Object[] tmp = new Object[]{i.getMaMonHoc(),i.getTenMonHoc(),i.getSoTinChi()};
                defaultTableModel.addRow(tmp);
            }
            ListSelectionModel listSelectionModel = danhSachMonHoc.getSelectionModel();
            listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            listSelectionModel.addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int[] dong = danhSachMonHoc.getSelectedRows();
                    int[] cot = danhSachMonHoc.getSelectedColumns();
                    String maMonHoc = String.valueOf(danhSachMonHoc.getValueAt(dong[0], 0));
                    String tenMonHoc = String.valueOf(danhSachMonHoc.getValueAt(dong[0], 1));
                    int soTinChi = (int)(danhSachMonHoc.getValueAt(dong[0], 2));


                    monhocChon = giaoVuService.layThongTinMonHocBangMaMonHoc(maMonHoc);

                    System.out.println(monhocChon.toString());
                    if (monhocChon != null) {
                        layMaMonHoc.setText(monhocChon.getMaMonHoc());
                        layTenMonHoc.setText(monhocChon.getTenMonHoc());
                        laySoTinChi.setText(monhocChon.getSoTinChi().toString());

                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeQuanLyMonHoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        maMonHoc = new javax.swing.JLabel();
        layMaMonHoc = new javax.swing.JTextField();
        tenMonHoc = new javax.swing.JLabel();
        laySoTinChi = new javax.swing.JTextField();
        soTinChi = new javax.swing.JLabel();
        layTenMonHoc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        themMonHoc = new javax.swing.JButton();
        suaMonHoc = new javax.swing.JButton();
        xoaMonHoc = new javax.swing.JButton();
        lamMoiDanhSach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachMonHoc = new javax.swing.JTable();

        tieuDeQuanLyMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tieuDeQuanLyMonHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieuDeQuanLyMonHoc.setText("Quản Lý Môn Học");
        tieuDeQuanLyMonHoc.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(tieuDeQuanLyMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tieuDeQuanLyMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 818, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 202, Short.MAX_VALUE)
        );

        maMonHoc.setText("Mã Môn Học");

        tenMonHoc.setText("Tên Môn Học");

        soTinChi.setText("Số Tín Chỉ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(soTinChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tenMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(maMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(laySoTinChi)
                                        .addComponent(layMaMonHoc)
                                        .addComponent(layTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(layTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(laySoTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(soTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        themMonHoc.setText("Thêm");
        themMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMonHocActionPerformed(evt);
            }
        });

        suaMonHoc.setText("Sửa");
        suaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaMonHocActionPerformed(evt);
            }
        });

        xoaMonHoc.setText("Xóa");
        xoaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaMonHocActionPerformed(evt);
            }
        });

        lamMoiDanhSach.setText("Làm Mới");
        lamMoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiDanhSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lamMoiDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(xoaMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(suaMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(themMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(themMonHoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suaMonHoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xoaMonHoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lamMoiDanhSach)
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        danhSachMonHoc.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Mã Môn Học", "Tên Môn Học", "Số Tín Chỉ"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(danhSachMonHoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(155, Short.MAX_VALUE)))
        );
    }// </editor-fold>

    private void themMonHocActionPerformed(java.awt.event.ActionEvent evt) {
        String strNull = "";
        String maMonHoc = layMaMonHoc.getText();
        String tenMonHoc = layTenMonHoc.getText();
        String stSoTinChi = laySoTinChi.getText();
        int sotinChi = 0;
        try {
            sotinChi = Integer.parseInt(stSoTinChi);
        }catch (Exception e){
            System.err.println(e);
            sotinChi = 0;
        }
        if(maMonHoc.equals(strNull) || tenMonHoc.equals(strNull) || stSoTinChi.equals(strNull)){
            JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu!!");
            this.ResetForm();
            return;
        }else {
            Monhoc monhonMoi = new Monhoc(maMonHoc, tenMonHoc, sotinChi);
            if (giaoVuService.themMonHocMoi(monhonMoi)) {
                JOptionPane.showMessageDialog(this, "Thêm Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi Không Thêm Được Mời Kiểm Tra Lại Dữ Liệu !");
                this.ResetForm();
            }
        }
    }

    private void suaMonHocActionPerformed(java.awt.event.ActionEvent evt) {
        if(monhocChon != null) {


            String strNull = "";
            String maMonHoc = layMaMonHoc.getText();
            String tenMonHoc1 = layTenMonHoc.getText();
            String stSoTinChi = laySoTinChi.getText();
            int sotinChi1 = 0;
            try {
                sotinChi1 = Integer.parseInt(stSoTinChi);
            } catch (Exception e) {
                System.err.println(e);
                sotinChi1 = 0;
            }
            if (maMonHoc.equals(strNull) || tenMonHoc.equals(strNull) || stSoTinChi.equals(strNull)) {
                JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu!!");
                this.ResetForm();
                return;
            }


            if (!monhocChon.getMaMonHoc().equals(maMonHoc)) {
                JOptionPane.showMessageDialog(null, "Mã Môn Học Không Được Đổi !!");
                this.ResetForm();
                return;
            }
            if (monhocChon != null) {
                monhocChon.setTenMonHoc(tenMonHoc1);
                monhocChon.setSoTinChi(sotinChi1);

                if (giaoVuService.capNhatMonHoc(monhocChon)) {
                    JOptionPane.showMessageDialog(this, "Sửa Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Lỗi Không Sửa Được Mời Kiểm Tra Lại Dữ Liệu !");
                    this.ResetForm();
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Chưa Chọn Giáo Vụ !");
            this.ResetForm();
        }
    }

    private void xoaMonHocActionPerformed(java.awt.event.ActionEvent evt) {
        if(monhocChon == null){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Môn Học Cần Xóa!");
            this.ResetForm();
        }
        else {
            String strNull = "";
            String maMonHoc = layMaMonHoc.getText();
            String tenMonHoc = layTenMonHoc.getText();
            String stSoTinChi = laySoTinChi.getText();
            int sotinChi = 0;
            try {
                sotinChi = Integer.parseInt(stSoTinChi);
            }catch (Exception e){
                System.err.println(e);
                sotinChi = 0;
            }
            if(maMonHoc.equals(strNull) || tenMonHoc.equals(strNull) || stSoTinChi.equals(strNull)){
                JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu!!");
                this.ResetForm();
                return;
            }else {
                if (giaoVuService.xoaMonHoc(monhocChon)) {
                    JOptionPane.showMessageDialog(this, "Xóa  Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa Không Thành Công!! Mời Kiểm Tra Lại Dữ Liệu");
                    this.ResetForm();
                }
            }
        }
    }

    private void lamMoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {
        ResetForm();
    }

    public void ResetForm() {
        layMaMonHoc.setText("");
        layTenMonHoc.setText("");
        laySoTinChi.setText("");
        monhocChon = null;
    }

    // Variables declaration - do not modify
    private javax.swing.JTable danhSachMonHoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoiDanhSach;
    private javax.swing.JTextField layMaMonHoc;
    private javax.swing.JTextField laySoTinChi;
    private javax.swing.JTextField layTenMonHoc;
    private javax.swing.JLabel maMonHoc;
    private javax.swing.JLabel soTinChi;
    private javax.swing.JButton suaMonHoc;
    private javax.swing.JLabel tenMonHoc;
    private javax.swing.JButton themMonHoc;
    private javax.swing.JLabel tieuDeQuanLyMonHoc;
    private javax.swing.JButton xoaMonHoc;
    // End of variables declaration
}
