/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Giaovien;
import model.Hocphanmo;
import model.Monhoc;
import service.GiaoVuService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.List;

/**
 *
 * @author lhqua
 */
public class FormQuanLyGiaoVien extends javax.swing.JFrame {
    private GiaoVuService giaoVuService = new GiaoVuService();
    private Giaovien giaovienChon = null;
    /**
     * Creates new form FormQuanLyGiaoVien
     */
    public FormQuanLyGiaoVien() {
        initComponents();
        capNhatDanhSachGiaoVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        thoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachGiaoVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        maGiaoVien = new javax.swing.JLabel();
        tenGiaoVien = new javax.swing.JLabel();
        gioiTinh = new javax.swing.JLabel();
        layMaGiaoVien = new javax.swing.JTextField();
        layTenGiaoVien = new javax.swing.JTextField();
        layGioiTinh = new javax.swing.JComboBox<>();
        ngaySinh = new javax.swing.JLabel();
        diaChi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        layNgaySinh = new javax.swing.JTextField();
        layDiaChi = new javax.swing.JTextField();
        layMonHoc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        themGiaoVien = new javax.swing.JButton();
        xoaGiaoVien = new javax.swing.JButton();
        lamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quản Lý Giáo Viên");

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(400, 400, 400)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(thoat))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        danhSachGiaoVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "Mã Giáo Viên", "Tên Giáo Viên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "Mã Môn Học"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        danhSachGiaoVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhSachGiaoVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(danhSachGiaoVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );

        maGiaoVien.setText("Mã Giáo Viên");

        tenGiaoVien.setText("Tên Giáo Viên");

        gioiTinh.setText("Giới Tính");

        layGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        ngaySinh.setText("Ngày Sinh");

        diaChi.setText("Địa Chỉ");

        jLabel7.setText("Mã Môn Học");

        themGiaoVien.setText("Thêm");
        themGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themGiaoVienActionPerformed(evt);
            }
        });

        xoaGiaoVien.setText("Xóa");
        xoaGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaGiaoVienActionPerformed(evt);
            }
        });

        lamMoi.setText("Làm Mới");
        lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(themGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xoaGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(themGiaoVien)
                                .addGap(18, 18, 18)
                                .addComponent(xoaGiaoVien)
                                .addGap(18, 18, 18)
                                .addComponent(lamMoi)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setText("YYYY-MM-DD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tenGiaoVien)
                                        .addComponent(gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(layMaGiaoVien)
                                                .addComponent(layTenGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                        .addComponent(layGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(layNgaySinh)
                                                .addComponent(layDiaChi)
                                                .addComponent(layMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maGiaoVien)
                                        .addComponent(layMaGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ngaySinh)
                                        .addComponent(layNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenGiaoVien)
                                        .addComponent(layTenGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(diaChi)
                                        .addComponent(layDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gioiTinh)
                                        .addComponent(layGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(layMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void danhSachGiaoVienMouseClicked(java.awt.event.MouseEvent evt) {
        int dong = danhSachGiaoVien.getSelectedRow();
        int[] cot = danhSachGiaoVien.getSelectedColumns();
        String maGiaoVien = String.valueOf(danhSachGiaoVien.getValueAt(dong, 0));
        String tenGiaoVien =  String.valueOf(danhSachGiaoVien.getValueAt(dong, 1));
        String gioiTinh = String.valueOf(danhSachGiaoVien.getValueAt(dong, 2));
        String ngaySinh = String.valueOf(danhSachGiaoVien.getValueAt(dong, 3));
        String diaChi = String.valueOf(danhSachGiaoVien.getValueAt(dong, 4));
        String maMonHoc = String.valueOf(danhSachGiaoVien.getValueAt(dong, 5));

        layMaGiaoVien.setText(maGiaoVien);
        layTenGiaoVien.setText(tenGiaoVien);
        if(gioiTinh.equals("Nam")){
            layGioiTinh.setSelectedIndex(0);
        }
        else{
            layGioiTinh.setSelectedIndex(1);
        }
        layNgaySinh.setText(ngaySinh);
        layDiaChi.setText(diaChi);
        layMonHoc.setText(maMonHoc);
        giaovienChon = giaoVuService.layGiaoVienBangMaGiaoVien(maGiaoVien);
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void themGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {
        String strNull="";
        String maGiaoVien = layMaGiaoVien.getText();
        String tenGiaoVien =  layTenGiaoVien.getText();
        String gioiTinh = layGioiTinh.getSelectedItem().toString();
        String ngaySinh = layNgaySinh.getText();
        String diaChi = layDiaChi.getText();
        String maMonHoc = layMonHoc.getText();
        if(maGiaoVien.equals(strNull) || tenGiaoVien.equals(strNull) || gioiTinh.equals(strNull) || ngaySinh.equals(strNull)){
            JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu !");
            this.ResetForm();
            return;
        }
        if(ngaySinh.charAt(4) != '-'|| ngaySinh.charAt(7) != '-' ){
            JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
            this.ResetForm();
            return;
        }
        Date date = Date.valueOf(ngaySinh);
        Monhoc monhoc = giaoVuService.layThongTinMonHocBangMaMonHoc(maMonHoc);
        if(monhoc == null){
            JOptionPane.showMessageDialog(null, "Không Tồn Tại Môn Học !! Mời Kiểm Tra Lại");
            this.ResetForm();
            return;
        }
        Giaovien giaovienMoi = new Giaovien(maGiaoVien,tenGiaoVien,gioiTinh,date,diaChi,monhoc);
        if(giaoVuService.themGiaoVien(giaovienMoi)){
            JOptionPane.showMessageDialog(this, "Thêm Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            capNhatDanhSachGiaoVien();
        }
        else{
            JOptionPane.showMessageDialog(null, "Lỗi Không Thêm Được Mời Kiểm Tra Lại Dữ Liệu !");
            this.ResetForm();
        }
    }

    private void xoaGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {
        if(giaovienChon == null){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Giáo Viên Cần Xóa!");
            this.ResetForm();
        }
        else{
            if(giaoVuService.xoaGiaoVien(giaovienChon)){
                JOptionPane.showMessageDialog(this, "Xóa  Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                giaovienChon = null;
                capNhatDanhSachGiaoVien();
            }
            else{
                JOptionPane.showMessageDialog(null, "Xóa Không Thành Công!! Mời Kiểm Tra Lại Dữ Liệu");
                this.ResetForm();
            }
        }
    }

    private void lamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        capNhatDanhSachGiaoVien();
        ResetForm();
    }
    private void ResetForm(){
        layMaGiaoVien.setText("");
        layTenGiaoVien.setText("");
        layGioiTinh.setSelectedIndex(0);
        layNgaySinh.setText("");
        layDiaChi.setText("");
        layMonHoc.setText("");
    }

    void capNhatDanhSachGiaoVien(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachGiaoVien.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Giáo Viên");
        defaultTableModel.addColumn("Tên Tên Giáo Viên");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("Địa Chỉ");
        defaultTableModel.addColumn("Mã Môn Học");
        List<Giaovien> danhSachGiaoVienDay = giaoVuService.layDanhSachGiaoVien();
        for (Giaovien i: danhSachGiaoVienDay) {
            Object[] tmp = new Object[]{i.getMaGiaoVien(), i.getTenGiaoVien(), i.getGioiTinh(), i.getNgaySinh().toString(), i.getDiaChi(),i.getMonHoc().getMaMonHoc()};
            defaultTableModel.addRow(tmp);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyGiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyGiaoVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTable danhSachGiaoVien;
    private javax.swing.JLabel diaChi;
    private javax.swing.JLabel gioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoi;
    private javax.swing.JTextField layDiaChi;
    private javax.swing.JComboBox<String> layGioiTinh;
    private javax.swing.JTextField layMaGiaoVien;
    private javax.swing.JTextField layMonHoc;
    private javax.swing.JTextField layNgaySinh;
    private javax.swing.JTextField layTenGiaoVien;
    private javax.swing.JLabel maGiaoVien;
    private javax.swing.JLabel ngaySinh;
    private javax.swing.JLabel tenGiaoVien;
    private javax.swing.JButton themGiaoVien;
    private javax.swing.JButton thoat;
    private javax.swing.JButton xoaGiaoVien;
    // End of variables declaration
}
