/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Giaovu;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

import static GUI.DangNhap.giaoVuService;

/**
 *
 * @author lhqua
 */
public class FormDanhSachGiaoVu extends javax.swing.JPanel {

    /**
     * Creates new form FormDanhSachGiaoVu
     */
    public FormDanhSachGiaoVu() {
        initComponents();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachGiaoVu.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Giáo Vụ");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("Địa Chỉ");
        List<Giaovu> listGiaoVu = giaoVuService.layDanhSachGiaoVu();
        for (Giaovu i : listGiaoVu) {
            Object[] tmp = new Object[]{i.getMaGiaoVu(), i.getTenGiaoVu(), i.getGioiTinh(), i.getNgaySinh().toString(), i.getDiaChi()};
            defaultTableModel.addRow(tmp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeGiaovu = new javax.swing.JLabel();
        lamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        maGiaoVu = new javax.swing.JLabel();
        layMaGiaoVu = new javax.swing.JTextField();
        timKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachGiaoVu = new javax.swing.JTable();

        tieuDeGiaovu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tieuDeGiaovu.setText("Danh Sách Giáo Vụ");

        lamMoi.setText("Làm Mới");
        lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(404, 404, 404)
                                .addComponent(tieuDeGiaovu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tieuDeGiaovu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lamMoi))
                                .addContainerGap())
        );

        maGiaoVu.setText("Nhập Mã Giáo Vụ Cần Tìm");

        timKiem.setText("Tìm Kiếm");
        timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(maGiaoVu)
                                .addGap(35, 35, 35)
                                .addComponent(layMaGiaoVu, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(maGiaoVu)
                                        .addComponent(layMaGiaoVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timKiem))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        danhSachGiaoVu.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Mã Giáo Vụ", "Tên Giáo Vụ", "Giới Tính", "Ngày Sinh", "Địa Chỉ"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(danhSachGiaoVu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void timKiemActionPerformed(java.awt.event.ActionEvent evt) {
        String strNull = "";
        String maSoGiaoVu = layMaGiaoVu.getText();
        if(maSoGiaoVu.equals(strNull)){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Nhập Mã Số Giáo Vụ Cần Tìm !!");
            return;
        }
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachGiaoVu.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Giáo Vụ");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("Địa Chỉ");
        List<Giaovu> listGiaoVu = giaoVuService.layDanhSachGiaoVu();
        for (Giaovu i : listGiaoVu) {
            if(i.getMaGiaoVu().equals(maSoGiaoVu)) {
                Object[] tmp = new Object[]{i.getMaGiaoVu(), i.getTenGiaoVu(), i.getGioiTinh(), i.getNgaySinh().toString(), i.getDiaChi()};
                defaultTableModel.addRow(tmp);
            }
        }
        layMaGiaoVu.setText("");
        layMaGiaoVu.requestFocus();
    }

    private void lamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachGiaoVu.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Giáo Vụ");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("Địa Chỉ");
        List<Giaovu> listGiaoVu = giaoVuService.layDanhSachGiaoVu();
        for (Giaovu i : listGiaoVu) {
            Object[] tmp = new Object[]{i.getMaGiaoVu(), i.getTenGiaoVu(), i.getGioiTinh(), i.getNgaySinh().toString(), i.getDiaChi()};
            defaultTableModel.addRow(tmp);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JTable danhSachGiaoVu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoi;
    private javax.swing.JTextField layMaGiaoVu;
    private javax.swing.JLabel maGiaoVu;
    private javax.swing.JLabel tieuDeGiaovu;
    private javax.swing.JButton timKiem;
    // End of variables declaration
}
