/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static GUI.DangNhap.*;

/**
 *
 * @author lhqua
 */
public class FormDanhSachHocPhanDaDangKi extends javax.swing.JFrame {
    private Hocki hockiHienTai = null;
    private Thoigiandkhp thoigiandkhpHienTai = null;
    private Sinhvien_Hocphan sinhvien_hocphanDangKi = null;
    private Set<Hocphanmo> danhSachDaDangKi = new HashSet<Hocphanmo>(0);
    public FormDanhSachHocPhanDaDangKi() {

        List<Hocki> hockiList = giaoVuService.layDanhSachHocKi();
        for (Hocki i: hockiList) {
            if(i.getSetHientai().equals(1)){
                hockiHienTai = i;
                break;
            }
        }
        Thoigiandkhp thoigiandkhp = giaoVuService.layThongtinThoiGianDKHPHienTai(hockiHienTai.getTenHocKi(),hockiHienTai.getNamHoc());
        thoigiandkhpHienTai = thoigiandkhp;

        Sinhvien sinhvienDangKi = giaoVuService.laySinhVienBangMaSinhVien(sinhvien.getMaSinhVien());
        Set<Sinhvien_Hocphan> sinhvien_hocphans = sinhvienDangKi.getSinhvien_hocphans();
        for (Sinhvien_Hocphan i: sinhvien_hocphans) {
            if(i.getHocphanmo().getThoigiandkhp().equals(thoigiandkhpHienTai)){
                danhSachDaDangKi.add(i.getHocphanmo());
            }
        }
        initComponents();
        capNhatDanhSachDaDangKi();
        long millis = System.currentTimeMillis();
        Date ngayHienTai = new Date(millis);
        Date ngayBatDau = thoigiandkhpHienTai.getNgayBatDau();
        Date ngayKetThuc = thoigiandkhpHienTai.getNgayKetThuc();
        if (ngayHienTai.after(ngayBatDau) && ngayHienTai.before(ngayKetThuc)) {
            huyDangKi.setEnabled(true);
        }
        else{
            huyDangKi.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeLichHoc = new javax.swing.JLabel();
        thoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachHocPhanDangKi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        huyDangKi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieuDeLichHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tieuDeLichHoc.setText("Danh Sách Lịch Học Đã Đăng Kí");

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tieuDeLichHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)
                                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tieuDeLichHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(thoat))
                                .addContainerGap())
        );

        danhSachHocPhanDangKi.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Mã Môn Học", "Tên Học Phần", "Phòng Học", "Thứ", "Ca"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        danhSachHocPhanDangKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhSachHocPhanDangKiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(danhSachHocPhanDangKi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );

        huyDangKi.setText("Hủy Đăng Kí");
        huyDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyDangKiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(745, Short.MAX_VALUE)
                                .addComponent(huyDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(huyDangKi)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void huyDangKiActionPerformed(java.awt.event.ActionEvent evt) {
        if(sinhvien_hocphanDangKi == null){
            JOptionPane.showMessageDialog(null, "Chưa Chọn Lớp Học Cần Xóa !!");
        }
        else{
            if(sinhVienService.xoaSinhVienTrongHocPhan(sinhvien_hocphanDangKi)){
                JOptionPane.showMessageDialog(null, "Hủy Thành Công !!");
                danhSachDaDangKi.remove(sinhvien_hocphanDangKi.getHocphanmo());
                capNhatDanhSachDaDangKi();
            }
            else{
                JOptionPane.showMessageDialog(null, "Hủy Không Thành Công !!");
            }
        }
    }

    private void danhSachHocPhanDangKiMouseClicked(java.awt.event.MouseEvent evt) {
        int dong = danhSachHocPhanDangKi.getSelectedRow();
        int[] cot = danhSachHocPhanDangKi.getSelectedColumns();
        String maMonHoc = String.valueOf(danhSachHocPhanDangKi.getValueAt(dong, 0));
        String tenHocPhan=  String.valueOf(danhSachHocPhanDangKi.getValueAt(dong, 1));
        String tenPhongHoc = String.valueOf(danhSachHocPhanDangKi.getValueAt(dong, 2));
        String thu = String.valueOf(danhSachHocPhanDangKi.getValueAt(dong, 3));
        String strCa = String.valueOf(danhSachHocPhanDangKi.getValueAt(dong, 4));

        Sinhvien sinhvienDangKi = sinhvien;
        Hocphanmo hocphanmo = null;
        for (Hocphanmo i : danhSachDaDangKi) {
            if(i.getMonhoc().getMaMonHoc().equals(maMonHoc) && i.getTenHocPhan().equals(tenHocPhan)){
                hocphanmo = i;
                break;
            }
        }
        Set<Sinhvien_Hocphan> danhSachHocPhanDangKi = sinhvienDangKi.getSinhvien_hocphans();
        for (Sinhvien_Hocphan i: danhSachHocPhanDangKi) {
            if(i.getHocphanmo().equals(hocphanmo)){
                sinhvien_hocphanDangKi = i;
                break;
            }
        }
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void capNhatDanhSachDaDangKi(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachHocPhanDangKi.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Học Phần");
        defaultTableModel.addColumn("Tên Phòng Học");
        defaultTableModel.addColumn("Thứ");
        defaultTableModel.addColumn("Ca");
        for (Hocphanmo i: danhSachDaDangKi) {
            Object[] tmp = new Object[]{i.getMonhoc().getMaMonHoc(), i.getTenHocPhan(), i.getTenPhongHoc(), i.getThu(), i.getCa().toString()};
            defaultTableModel.addRow(tmp);
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JTable danhSachHocPhanDangKi;
    private javax.swing.JButton huyDangKi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton thoat;
    private javax.swing.JLabel tieuDeLichHoc;
    // End of variables declaration
}
