/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Hocki;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import java.sql.Date;
import java.util.List;

import static GUI.DangNhap.giaoVuService;
import static GUI.DangNhap.kiemTraNguoiDung;

/**
 *
 * @author lhqua
 */
public class FormQuanLyHocKi extends javax.swing.JPanel {
    private Hocki hockiChon = null;

    /**
     * Creates new form FormQuanLyHocKi
     */
    public FormQuanLyHocKi() {
        initComponents();
        capNhatDanhSachHocKi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeHocKi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachHocKi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tenHocKi = new javax.swing.JLabel();
        layTenHocKi = new javax.swing.JTextField();
        tenNamHoc = new javax.swing.JLabel();
        layNgayBatDau = new javax.swing.JTextField();
        ngayBatDau = new javax.swing.JLabel();
        layNamHoc = new javax.swing.JTextField();
        ngayKetThuc = new javax.swing.JLabel();
        layNgayKetThuc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        themHocKi = new javax.swing.JButton();
        suaHocKi = new javax.swing.JButton();
        xoaHocKi = new javax.swing.JButton();
        lamMoiDanhSach = new javax.swing.JButton();
        setHocKiHienTai = new javax.swing.JButton();

        tieuDeHocKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tieuDeHocKi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieuDeHocKi.setText("Quản Lý Học Kì");
        tieuDeHocKi.setName(""); // NOI18N

        danhSachHocKi.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Tên Học Kì", "Năm Học", "Ngày Bắt Đầu", "Ngày Kết Thúc"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        danhSachHocKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhSachHocKiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(danhSachHocKi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(tieuDeHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tieuDeHocKi, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        tenHocKi.setText("Tên Học Kì");

        tenNamHoc.setText("Năm Học");

        ngayBatDau.setText("Ngày Bắt Đầu");

        ngayKetThuc.setText("Ngày Kết Thúc");

        jLabel1.setText("YYYY-MM-DD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(tenNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(layNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(tenHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(layTenHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(ngayKetThuc)
                                                .addGap(18, 18, 18)
                                                .addComponent(layNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(ngayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(layNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layTenHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ngayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tenNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ngayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(43, Short.MAX_VALUE))
        );

        themHocKi.setText("Thêm");
        themHocKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themHocKiActionPerformed(evt);
            }
        });

        suaHocKi.setText("Sửa");
        suaHocKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaHocKiActionPerformed(evt);
            }
        });

        xoaHocKi.setText("Xóa");
        xoaHocKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaHocKiActionPerformed(evt);
            }
        });

        lamMoiDanhSach.setText("Làm Mới");
        lamMoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiDanhSachActionPerformed(evt);
            }
        });

        setHocKiHienTai.setText("Set Học Kì Hiện Tại");
        setHocKiHienTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setHocKiHienTaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(xoaHocKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(suaHocKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(themHocKi, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(setHocKiHienTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lamMoiDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lamMoiDanhSach)
                                                .addGap(33, 33, 33)
                                                .addComponent(setHocKiHienTai)
                                                .addGap(7, 7, 7))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(themHocKi)
                                                .addGap(28, 28, 28)
                                                .addComponent(suaHocKi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                                .addComponent(xoaHocKi)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>

    private void themHocKiActionPerformed(java.awt.event.ActionEvent evt) {
        String strNull = "";
        String tenHocKi = layTenHocKi.getText();
        String strNamHoc = layNamHoc.getText();
        String ngayBatDau = layNgayBatDau.getText();
        String ngayKetThuc = layNgayKetThuc.getText();
        int namHoc = 0;
        try {
            namHoc = Integer.parseInt(strNamHoc);
        }catch (Exception e){
            System.err.println(e);
            namHoc = 0;
        }
        if(tenHocKi.equals(strNull) || strNamHoc.equals(strNull) || ngayBatDau.equals(strNull) || ngayKetThuc.equals(strNull)) {
            JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu!!");
            this.ResetForm();
            return;
        }
        if(ngayBatDau.charAt(4) != '-'|| ngayKetThuc.charAt(7) != '-' ){
            JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
            this.ResetForm();
            return;
        }
        Date dateBatDau = Date.valueOf(ngayBatDau);
        Date dateKetThuc = Date.valueOf(ngayKetThuc);
        Hocki hockiMoi = new Hocki(tenHocKi,namHoc,dateBatDau,0,dateKetThuc);

        if(giaoVuService.themHocKiMoi(hockiMoi)){
            JOptionPane.showMessageDialog(this, "Thêm Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            capNhatDanhSachHocKi();
        }
        else{
            JOptionPane.showMessageDialog(null, "Lỗi Không Thêm Được Mời Kiểm Tra Lại Dữ Liệu !");
            this.ResetForm();
        }
    }

    private void suaHocKiActionPerformed(java.awt.event.ActionEvent evt) {
        if(hockiChon == null){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Môn Học Cần Xóa!");
            this.ResetForm();
        }
        else {
            String strNull = "";
            String tenHocKi = layTenHocKi.getText();
            String strNamHoc = layNamHoc.getText();
            String ngayBatDau = layNgayBatDau.getText();
            String ngayKetThuc = layNgayKetThuc.getText();
            int namHoc = 0;
            try {
                namHoc = Integer.parseInt(strNamHoc);
            } catch (Exception e) {
                System.err.println(e);
                namHoc = 0;
            }
            if (tenHocKi.equals(strNull) || strNamHoc.equals(strNull) || ngayBatDau.equals(strNull) || ngayKetThuc.equals(strNull)) {
                JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu!!");
                this.ResetForm();
                return;
            }
            if (ngayBatDau.charAt(4) != '-' || ngayKetThuc.charAt(7) != '-') {
                JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
                this.ResetForm();
                return;
            }
            Date dateBatDau = Date.valueOf(ngayBatDau);
            Date dateKetThuc = Date.valueOf(ngayKetThuc);
            Hocki hockiSua = giaoVuService.layThongTinHocKiHienTai(tenHocKi,namHoc);
            hockiSua.setNgayBatDau(dateBatDau);
            hockiSua.setNgayKetThuc(dateKetThuc);
            if (giaoVuService.capNhatHocKi(hockiSua)) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                capNhatDanhSachHocKi();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi Không Cập Nhật Được Mời Kiểm Tra Lại Dữ Liệu !");
                this.ResetForm();
            }
        }
    }

    private void xoaHocKiActionPerformed(java.awt.event.ActionEvent evt) {
        if(hockiChon == null){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Học Kì Cần Xóa!");
            this.ResetForm();
        }
        else{
            String strNull = "";
            String tenHocKi = layTenHocKi.getText();
            String stNamHoc = layNamHoc.getText();
            String ngayBatDau = layNgayBatDau.getText();
            String ngayKetThuc = layNgayKetThuc.getText();
            int namHoc = 0;
            try {
                namHoc = Integer.parseInt(stNamHoc);
            }catch (Exception e){
                System.err.println(e);
                namHoc = 0;
            }
            if(tenHocKi.equals(strNull) || stNamHoc.equals(strNull) || ngayBatDau.equals(strNull) || ngayKetThuc.equals(strNull)){
                JOptionPane.showMessageDialog(null, "Không Được Để Trống Các Ô Dữ Liệu!!");
                this.ResetForm();
                return;
            }else {
                if (giaoVuService.xoaHocKi(tenHocKi,namHoc)) {
                    JOptionPane.showMessageDialog(this, "Xóa  Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    capNhatDanhSachHocKi();
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa Không Thành Công!! Mời Kiểm Tra Lại Dữ Liệu");
                    this.ResetForm();
                }
            }
        }
    }

    private void lamMoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {
        capNhatDanhSachHocKi();
        ResetForm();
    }

    private void setHocKiHienTaiActionPerformed(java.awt.event.ActionEvent evt) {
        if(hockiChon == null){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Học Kì Set");
            this.ResetForm();
        }
        else {
            List<Hocki> hockis = giaoVuService.layDanhSachHocKi();
            for (Hocki i : hockis) {
                i.setSetHientai(0);
                giaoVuService.capNhatHocKi(i);
            }
            hockiChon.setSetHientai(1);
            if (!giaoVuService.capNhatHocKi(hockiChon)) {
                JOptionPane.showMessageDialog(null, "Set Học Kì Thất Bại!! Mời Kiểm Tra Lại !!");
                this.ResetForm();
            } else {

                JOptionPane.showMessageDialog(this, "Set Học Kì Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void danhSachHocKiMouseClicked(java.awt.event.MouseEvent evt) {
        int dong = danhSachHocKi.getSelectedRow();
        int[] cot = danhSachHocKi.getSelectedColumns();
        String tenHocKi = String.valueOf(danhSachHocKi.getValueAt(dong, 0));
        int namHoc = (int) (danhSachHocKi.getValueAt(dong, 1));
        String ngayBatDau = String.valueOf(danhSachHocKi.getValueAt(dong, 2));
        String ngayKetThuc = String.valueOf(danhSachHocKi.getValueAt(dong, 3));


        hockiChon = giaoVuService.layThongTinHocKiHienTai(tenHocKi,namHoc);

        System.out.println(hockiChon.toString());
        if (hockiChon != null) {
            layTenHocKi.setText(hockiChon.getTenHocKi());
            layNamHoc.setText(hockiChon.getNamHoc().toString());
            layNgayBatDau.setText(hockiChon.getNgayBatDau().toString());
            layNgayKetThuc.setText(hockiChon.getNgayKetThuc().toString());
        }
    }


    private void capNhatDanhSachHocKi(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachHocKi.setModel(defaultTableModel);
        defaultTableModel.addColumn("Tên Học Kì");
        defaultTableModel.addColumn("Năm Học");
        defaultTableModel.addColumn("Ngày Bắt Đầu");
        defaultTableModel.addColumn("Ngày Kết Thúc");
        List<Hocki> listHocKi = giaoVuService.layDanhSachHocKi();
        for (Hocki i : listHocKi) {
            Object[] tmp = new Object[]{i.getTenHocKi(), i.getNamHoc(), i.getNgayBatDau().toString(),i.getNgayKetThuc().toString()};
            defaultTableModel.addRow(tmp);
        }
    }

    private void ResetForm() {
        layTenHocKi.setText("");
        layNamHoc.setText("");
        layNgayBatDau.setText("");
        layNgayKetThuc.setText("");
    }

    // Variables declaration - do not modify
    private javax.swing.JTable danhSachHocKi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoiDanhSach;
    private javax.swing.JTextField layNamHoc;
    private javax.swing.JTextField layNgayBatDau;
    private javax.swing.JTextField layNgayKetThuc;
    private javax.swing.JTextField layTenHocKi;
    private javax.swing.JLabel ngayBatDau;
    private javax.swing.JLabel ngayKetThuc;
    private javax.swing.JButton setHocKiHienTai;
    private javax.swing.JButton suaHocKi;
    private javax.swing.JLabel tenHocKi;
    private javax.swing.JLabel tenNamHoc;
    private javax.swing.JButton themHocKi;
    private javax.swing.JLabel tieuDeHocKi;
    private javax.swing.JButton xoaHocKi;
    // End of variables declaration
}
