/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.*;
import service.GiaoVuService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Set;

/**
 *
 * @author lhqua
 */
public class FormXemThongTinHocPhan extends javax.swing.JFrame {
    private GiaoVuService giaoVuService = new GiaoVuService();
    private Hocphanmo hocphanmo = null;
    /**
     * Creates new form FormXemThongTinHocPhan
     */
    public FormXemThongTinHocPhan(Hocphanmo hocphanmoChon) {
        hocphanmo = hocphanmoChon;
        initComponents();
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachSinhVienHocPhan.setModel(defaultTableModel);
        defaultTableModel.addColumn("MSSV");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Môn Học");
        defaultTableModel.addColumn("Giáo Viên Lý Thuyết");
        defaultTableModel.addColumn("Thời Gian Học");
        defaultTableModel.addColumn("Thời Gian Đăng Kí");
        if(hocphanmoChon != null){
            Set<Sinhvien_Hocphan> sinhviens = hocphanmoChon.getSinhvien_hocphans();

            Monhoc monhoc = hocphanmoChon.getMonhoc();
            Giaovien giaovien = giaoVuService.layGiaoVienBangMaGiaoVien(hocphanmoChon.getMaGvlt());
            Hocki hocki = hocphanmoChon.getThoigiandkhp().getHocki();
            String tenMonHoc = monhoc.getTenMonHoc();
            String maMonHoc =monhoc.getMaMonHoc();
            String tenGiaoVien = giaovien.getTenGiaoVien();
            String thoiGianHoc = hocki.getNgayBatDau().toString();
            for (Sinhvien_Hocphan i : sinhviens) {
                String mssv = i.getSinhvien().getMaSinhVien();
                String hoTen = i.getSinhvien().getTenSinhVien();
                String thoiGianDangKi = i.getNgayDangKi().toString();
                Object[] tmp = new Object[]{mssv,hoTen,maMonHoc,tenMonHoc,tenGiaoVien,thoiGianHoc,thoiGianDangKi};
                defaultTableModel.addRow(tmp);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeLopHocPhan = new javax.swing.JLabel();
        thoat = new javax.swing.JButton();
        lamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhSachSinhVienHocPhan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        timKiem = new javax.swing.JButton();
        layMaSinhVien = new javax.swing.JTextField();
        maSinhVien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieuDeLopHocPhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tieuDeLopHocPhan.setText("Thông Tin Lớp Học Phần");

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        lamMoi.setText("Làm Mới");
        lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tieuDeLopHocPhan)
                                .addGap(247, 247, 247)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(tieuDeLopHocPhan))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(thoat)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lamMoi)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        danhSachSinhVienHocPhan.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String [] {
                        "MSSV", "Họ Tên", "Mã Môn Học", "Tên Môn Học", "Giáo Viên Lý Thuyết", "Thời Gian Học", "Thời Gian Đăng Kí"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(danhSachSinhVienHocPhan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        timKiem.setText("Tìm Kiếm");
        timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemActionPerformed(evt);
            }
        });

        maSinhVien.setText("Nhập Mã Sinh Viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(maSinhVien)
                                .addGap(34, 34, 34)
                                .addComponent(layMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(timKiem)
                                        .addComponent(layMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maSinhVien))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void timKiemActionPerformed(java.awt.event.ActionEvent evt) {
        if(hocphanmo == null){
            return;
        }
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachSinhVienHocPhan.setModel(defaultTableModel);
        defaultTableModel.addColumn("MSSV");
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Mã Môn Học");
        defaultTableModel.addColumn("Tên Môn Học");
        defaultTableModel.addColumn("Giáo Viên Lý Thuyết");
        defaultTableModel.addColumn("Thời Gian Học");
        defaultTableModel.addColumn("Thời Gian Đăng Kí");
        String maSinhVien = layMaSinhVien.getText();
        String strNull = "";
        if(maSinhVien.equals(strNull)){
            JOptionPane.showMessageDialog(null, "Bạn Chưa Nhập Mã Số Sinh Viên Cần Tìm !!");
            return;
        }
        if(hocphanmo != null){
            Set<Sinhvien_Hocphan> sinhviens = hocphanmo.getSinhvien_hocphans();

            Monhoc monhoc = hocphanmo.getMonhoc();
            Giaovien giaovien = giaoVuService.layGiaoVienBangMaGiaoVien(hocphanmo.getMaGvlt());
            Hocki hocki = hocphanmo.getThoigiandkhp().getHocki();
            String tenMonHoc = monhoc.getTenMonHoc();
            String maMonHoc =monhoc.getMaMonHoc();
            String tenGiaoVien = giaovien.getTenGiaoVien();
            String thoiGianHoc = hocki.getNgayBatDau().toString();
            for (Sinhvien_Hocphan i : sinhviens) {
                String mssv = i.getSinhvien().getMaSinhVien();
                String hoTen = i.getSinhvien().getTenSinhVien();
                String thoiGianDangKi = i.getNgayDangKi().toString();
                if (mssv.equals(maSinhVien)) {
                    Object[] tmp = new Object[]{mssv,hoTen,maMonHoc,tenMonHoc,tenGiaoVien,thoiGianHoc,thoiGianDangKi};
                    defaultTableModel.addRow(tmp);
                }
            }
        }
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void lamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        new FormXemThongTinHocPhan(hocphanmo).setVisible(true);
        dispose();
    }



    // Variables declaration - do not modify
    private javax.swing.JTable danhSachSinhVienHocPhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoi;
    private javax.swing.JTextField layMaSinhVien;
    private javax.swing.JLabel maSinhVien;
    private javax.swing.JButton thoat;
    private javax.swing.JLabel tieuDeLopHocPhan;
    private javax.swing.JButton timKiem;
    // End of variables declaration
}
