/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author lhqua
 */
public class MainGiaoVu extends javax.swing.JFrame {

    /**
     * Creates new form MainGiaoVu
     */
    public MainGiaoVu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        content = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        xinChao = new javax.swing.JLabel();
        tenId = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        taiKhoan = new javax.swing.JMenu();
        xemThongTinTaiKhoan = new javax.swing.JMenuItem();
        thayDoiThongTin = new javax.swing.JMenuItem();
        quanLyMatKhau = new javax.swing.JMenuItem();
        dangXuat = new javax.swing.JMenuItem();
        thoat = new javax.swing.JMenuItem();
        quanLyCoBan = new javax.swing.JMenu();
        quanLyGiaoVu = new javax.swing.JMenuItem();
        quanLyLopHoc = new javax.swing.JMenuItem();
        quanLyMonHoc = new javax.swing.JMenuItem();
        quanLySinhVien = new javax.swing.JMenuItem();
        quanLyDaoTao = new javax.swing.JMenu();
        quanLyHocKi = new javax.swing.JMenuItem();
        quanLyDKHP = new javax.swing.JMenuItem();
        quanLyHocPhan = new javax.swing.JMenuItem();
        timKiem = new javax.swing.JMenu();
        timKiemGiaoVu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        xinChao.setText("Xin chào");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(xinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(911, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tenId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(xinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(394, Short.MAX_VALUE))
        );

        content.addTab("Trang Trủ", jPanel1);

        taiKhoan.setText("Tài Khoản");

        xemThongTinTaiKhoan.setText("Xem Thông Tin Tài Khoản");
        xemThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemThongTinTaiKhoanActionPerformed(evt);
            }
        });
        taiKhoan.add(xemThongTinTaiKhoan);

        thayDoiThongTin.setText("Thay Đổi Thông Tin");
        thayDoiThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thayDoiThongTinActionPerformed(evt);
            }
        });
        taiKhoan.add(thayDoiThongTin);

        quanLyMatKhau.setText("Đổi Mật Khẩu");
        quanLyMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyMatKhauActionPerformed(evt);
            }
        });
        taiKhoan.add(quanLyMatKhau);

        dangXuat.setText("Đăng Xuất");
        dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatActionPerformed(evt);
            }
        });
        taiKhoan.add(dangXuat);

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });
        taiKhoan.add(thoat);

        jMenuBar1.add(taiKhoan);

        quanLyCoBan.setText("Quản Lý Cơ Bản");

        quanLyGiaoVu.setText("Quản Lý Giáo Vụ");
        quanLyGiaoVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyGiaoVuActionPerformed(evt);
            }
        });
        quanLyCoBan.add(quanLyGiaoVu);

        quanLyLopHoc.setText("Quản Lý Lớp Học");
        quanLyLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyLopHocActionPerformed(evt);
            }
        });
        quanLyCoBan.add(quanLyLopHoc);

        quanLyMonHoc.setText("Quản Lý Môn Học");
        quanLyMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyMonHocActionPerformed(evt);
            }
        });
        quanLyCoBan.add(quanLyMonHoc);

        quanLySinhVien.setText("Quản Lý Sinh Viên");
        quanLySinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLySinhVienActionPerformed(evt);
            }
        });
        quanLyCoBan.add(quanLySinhVien);

        jMenuBar1.add(quanLyCoBan);

        quanLyDaoTao.setText("Quản Lý Đào Tạo");

        quanLyHocKi.setText("Quản Lý Học Kì");
        quanLyHocKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHocKiActionPerformed(evt);
            }
        });
        quanLyDaoTao.add(quanLyHocKi);

        quanLyDKHP.setText("Quản Lý Đăng Kí Học Phần");
        quanLyDKHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyDKHPActionPerformed(evt);
            }
        });
        quanLyDaoTao.add(quanLyDKHP);

        quanLyHocPhan.setText("Quản Lý Học Phần");
        quanLyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHocPhanActionPerformed(evt);
            }
        });
        quanLyDaoTao.add(quanLyHocPhan);

        jMenuBar1.add(quanLyDaoTao);

        timKiem.setText("Tìm Kiếm");

        timKiemGiaoVu.setText("Tìm Kiếm Giáo Vụ");
        timKiemGiaoVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemGiaoVuActionPerformed(evt);
            }
        });
        timKiem.add(timKiemGiaoVu);

        jMenuBar1.add(timKiem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void quanLyHocKiActionPerformed(java.awt.event.ActionEvent evt) {
        FormQuanLyHocKi quanLyHocKi = new FormQuanLyHocKi();
        quanLyMonHoc.show();
        content.removeAll();
        content.add("Quản Lý Học Kì", quanLyHocKi);
        //quanLyGiaoVu.ResetForm();
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void dangXuatActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        DangNhap dangNhap = new DangNhap();
        dangNhap.setVisible(true);
    }

    private void quanLyMatKhauActionPerformed(java.awt.event.ActionEvent evt) {
        DoiMatKhau doiMatKhau = new DoiMatKhau();
        doiMatKhau.show();
    }

    private void thayDoiThongTinActionPerformed(java.awt.event.ActionEvent evt) {
        ThayDoiThongTin thayDoiThongTin = new ThayDoiThongTin();
        thayDoiThongTin.show();
    }

    private void quanLyGiaoVuActionPerformed(java.awt.event.ActionEvent evt) {
        FormQuanLyGiaoVu quanLyGiaoVu = new FormQuanLyGiaoVu();
        quanLyGiaoVu.show();
        content.removeAll();
        content.add("Quản Lý Giáo Vụ", quanLyGiaoVu);
        //quanLyGiaoVu.ResetForm();
    }

    private void quanLyLopHocActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void quanLyMonHocActionPerformed(java.awt.event.ActionEvent evt) {
        FormMonHoc quanLyMonHoc = new FormMonHoc();
        quanLyMonHoc.show();
        content.removeAll();
        content.add("Quản Lý Môn Học", quanLyMonHoc);
    }

    private void quanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void quanLyDKHPActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void quanLyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void timKiemGiaoVuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void xemThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {
        ThongTinTaiKhoan thongTinTaiKhoan = new ThongTinTaiKhoan();
        thongTinTaiKhoan.show();
        content.removeAll();
        content.add("Thông Tin Tài Khoản", thongTinTaiKhoan);
        //thongTinTaiKhoan.ResetForm
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGiaoVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTabbedPane content;
    private javax.swing.JMenuItem dangXuat;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu quanLyCoBan;
    private javax.swing.JMenuItem quanLyDKHP;
    private javax.swing.JMenu quanLyDaoTao;
    private javax.swing.JMenuItem quanLyGiaoVu;
    private javax.swing.JMenuItem quanLyHocKi;
    private javax.swing.JMenuItem quanLyHocPhan;
    private javax.swing.JMenuItem quanLyLopHoc;
    private javax.swing.JMenuItem quanLyMatKhau;
    private javax.swing.JMenuItem quanLyMonHoc;
    private javax.swing.JMenuItem quanLySinhVien;
    private javax.swing.JMenu taiKhoan;
    private javax.swing.JLabel tenId;
    private javax.swing.JMenuItem thayDoiThongTin;
    private javax.swing.JMenuItem thoat;
    private javax.swing.JMenu timKiem;
    private javax.swing.JMenuItem timKiemGiaoVu;
    private javax.swing.JMenuItem xemThongTinTaiKhoan;
    private javax.swing.JLabel xinChao;
    // End of variables declaration
}
