/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.*;

import java.sql.Date;

import static GUI.DangNhap.*;

/**
 *
 * @author lhqua
 */
public class ThayDoiThongTin extends javax.swing.JFrame {

    /**
     * Creates new form ThayDoiThongTin
     */
    public ThayDoiThongTin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tieuDeThayDoiThongTin = new javax.swing.JLabel();
        gioiTinh = new javax.swing.JPanel();
        nhapTen = new javax.swing.JLabel();
        layTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        layGioiTinh = new javax.swing.JComboBox<>();
        ngaySinh = new javax.swing.JLabel();
        layNgaySinh = new javax.swing.JTextField();
        thayDoi = new javax.swing.JButton();
        diaChi = new javax.swing.JLabel();
        layDiaChi = new javax.swing.JTextField();
        thoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tieuDeThayDoiThongTin.setText("Thay Đổi Thông Tin ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(tieuDeThayDoiThongTin)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(tieuDeThayDoiThongTin)
                                .addGap(21, 21, 21))
        );

        nhapTen.setText("Nhập Tên");

        jLabel3.setText("Giới Tính");

        layGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        ngaySinh.setText("Ngày Sinh");

        thayDoi.setText("Thay Đổi");
        thayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thayDoiActionPerformed(evt);
            }
        });

        diaChi.setText("Địa Chỉ");

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        jLabel1.setText("YYYY-MM-DD");

        javax.swing.GroupLayout gioiTinhLayout = new javax.swing.GroupLayout(gioiTinh);
        gioiTinh.setLayout(gioiTinhLayout);
        gioiTinhLayout.setHorizontalGroup(
                gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(nhapTen))
                                                .addGap(18, 18, 18)
                                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                                                .addComponent(layGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(layTen)))
                                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ngaySinh)
                                                        .addComponent(diaChi))
                                                .addGap(18, 18, 18)
                                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(layDiaChi)
                                                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                                                .addComponent(layNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel1)
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())
                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(thayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(98, Short.MAX_VALUE))
        );
        gioiTinhLayout.setVerticalGroup(
                gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gioiTinhLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nhapTen)
                                        .addComponent(layTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(layGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(layNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diaChi)
                                        .addComponent(layDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(thayDoi)
                                        .addComponent(thoat))
                                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void thayDoiActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String stNull = "";
        String ten = layTen.getText();
        String gioiTinh = layGioiTinh.getSelectedItem().toString();
        String ngaySinh = layNgaySinh.getText();
        String diaChi = layDiaChi.getText();
        if(ten.equals(stNull) || gioiTinh.equals(stNull) || ngaySinh.equals(stNull)){
            JOptionPane.showMessageDialog(null, "Tài khoản và mật khẩu không được trống !");
            this.resetForm();
        }
        if(ngaySinh.charAt(4) != '-'|| ngaySinh.charAt(7) != '-' ){
            JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
            this.resetForm();
        }
        else{
            if(kiemTraNguoiDung == 0){
                Date date = Date.valueOf(ngaySinh);
                if(date == null){
                    JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
                    this.resetForm();
                }
                giaovu.setTenGiaoVu(ten);
                giaovu.setGioiTinh(gioiTinh);
                giaovu.setDiaChi(diaChi);
                giaovu.setNgaySinh(date);
                giaoVuService.capNhatGiaoVu(giaovu);
            }
            else if(kiemTraNguoiDung == 1){
                Date date = Date.valueOf(ngaySinh);
                if(date == null){
                    JOptionPane.showMessageDialog(null, "Ngày sinh nhập sai !!");
                    this.resetForm();
                }
                sinhvien.setTenSinhVien(ten);
                sinhvien.setGioiTinh(gioiTinh);
                sinhvien.setDiaChi(diaChi);
                sinhvien.setNgaySinh(date);
                sinhVienService.capNhatSinhVien(sinhvien);
            }
            JOptionPane.showMessageDialog(this, "Thay Đổi Thành Công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    public void resetForm() {
        layTen.setText("");
        layNgaySinh.setText("");
        layDiaChi.setText("");
        layTen.requestFocus();
    }



    // Variables declaration - do not modify
    private javax.swing.JLabel diaChi;
    private javax.swing.JPanel gioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField layDiaChi;
    private javax.swing.JComboBox<String> layGioiTinh;
    private javax.swing.JTextField layNgaySinh;
    private javax.swing.JTextField layTen;
    private javax.swing.JLabel ngaySinh;
    private javax.swing.JLabel nhapTen;
    private javax.swing.JButton thayDoi;
    private javax.swing.JButton thoat;
    private javax.swing.JLabel tieuDeThayDoiThongTin;
    // End of variables declaration
}
